### PR TITLE
Thrift needs to be compiled with -fPIC for static linking

### PR DESCRIPTION
**Pull request by wesm**
Missed this in the build recipe and ran into it when trying to build apache/parquet-cpp

### CODE REVIEW

**Comment by msarahan** [comment]
Yikes, that's a hairy template-madness error.  Relevant part seems to be at https://travis-ci.org/conda-forge/thrift-cpp-feedstock/builds/129890165#L1132

**Comment by wesm** [comment]
@msarahan that's a C++ stdlib linker issue (for some reason the default stdlib on apple doesn't play nice with C++11), usually setting `-stdlib=libc++` solves the problem, I changed it back to an environment variable to see if it goes away

**Comment by wesm** [comment]
Oh the joys of build systems.

**Comment by pelson** [comment]
@wesm - any easy way of testing this change in the recipe?

**Comment by wesm** [comment]
@pelson it's pretty difficult, the only way is to link the static library (`libthrift.a` here) into another shared library. I confirmed this as part of https://github.com/apache/parquet-cpp/pull/104 (where we are statically linking thrift, snappy, and zlib)

**Comment by msarahan** [comment]
IMHO, linking several static libs into a larger dynamic lib is a small but important use case.  Should we be creating our static libs all with -fPIC, or just on an individual basis?

**Comment by wesm** [comment]
Yes, definitely. In the meantime -- if you could look at https://github.com/conda-forge/snappy-feedstock/pull/1 and https://github.com/conda-forge/zlib-feedstock/pull/4.

I am not enough of an expert on compilers and linkers to understand the downside of -fPIC -- my understanding is that it can have performance implications (without it, the compiler may be able to inline code from a static library). This is fairly esoteric, though, and is probably not a conda-forge use case.

**Comment by jakirkham** [comment]
> Should we be creating our static libs all with -fPIC, or just on an individual basis?

Would prefer individual use case (i.e. per request). Sometimes these flags can have issues.

**Pull request merged**
