### PR TITLE
Thrift version update to 0.10.0; Windows build support.

### PR DESCRIPTION
**Pull request by maxhora**

### CODE REVIEW

**Comment by wesm** [comment]
Sweet! Any chance this builds with vc9 runtime for Python 2.7?

**Comment by maxhora** [comment]
@wesm , libevent build fails with vc9 here https://github.com/nmathewson/Libevent/blob/master/test/regress_http.c#L3610

**Comment by maxhora** [comment]
@wesm , have updated changes to build only with vc14 (since vc9 doesn't support C++11 and vc10 is not supported by conda-forge).
Interesting, that if `vc 14` is not added to the `run` subsection of `requirements` section ( https://github.com/conda-forge/thrift-cpp-feedstock/pull/13/files#diff-e178b687b10a71a3348107ae3154e44cR38 ) conda build fails with following error on last "Testing" stage:

> TEST START: C:\bld\win-32\thrift-cpp-0.10.0-vc14_0.tar.bz2
> Deleting work directory, C:\bld\thrift-cpp_1492595390462\work\thrift-0.10.0
> ...Can't build C:\projects\thrift-cpp-feedstock\recipe due to unsatisfiable dependencies:
> The following specifications were found to be in conflict:
>   - thrift-cpp 0.10.0 vc14_0 -> feature:vc14
> Use "conda info <package>" to see the dependencies for each package.
> Command exited with code 1

**Comment by jakirkham** [comment]
There are two ways to solve that issue. The original and most common way is to add `python` with the appropriate version as run time dependency as [seen here]( https://github.com/conda-forge/yasm-feedstock/blob/d95fea726a19b3ed8a84051fda44540b767a7aaa/recipe/meta.yaml#L26-L28 ). The other is adding the `vc` package with an appropriate version to `run` (and possibly `build` too).

**Comment by maxhora** [comment]
@jakirkham , thank you! This works great!

**Comment by wesm** [comment]
Looks good. Thanks @MaxRis!

**Pull request merged**
