### PR TITLE
Pin boost

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
I think we are only using shared pointers from Boost so this is a header only dependency. Though @wesm could you please comment, I think you know much more about `thrift` than I do.

**Comment by wesm** [comment]
Correct, this is header only. I'm fine with this, let me know if I should go ahead and merge

**Comment by jakirkham** [comment]
I don't think we need to. If we find the header from Boost 1.61.0 doesn't work for us, we can try merging this then.

**Comment by jakirkham** [comment]
Going to close this one out as this is header only. If we have surprises, we can re-open and pin.

**Pull request closed without merging**
