### PR TITLE
Update openssl to 1.1.1a

### LINKED ISSUE #24: Build for openssl 1.1*
As discussed on [gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5c614751604f233ab6edff29) `thrift-cpp` is currently only built against openssl `1.0.2p` whereas some newer libraries (e.g. `qt=5.9.7`) require `openssl=1.1*`

Since the recipe doesn't actually pin `openssl`:
https://github.com/conda-forge/thrift-cpp-feedstock/blob/c6c1d84ad21f58291ebcccb090ffe8f75b973dbc/recipe/meta.yaml#L40-L48

I'm not how to get `conda-forge` to build against the newer `openssl`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #24

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I doubt this is the right fix. I imagine `conda-forge` has some automated way to pin the dependency but I thought it would at least get the discussion started about the right way to fix it...

**Comment by dhirschfeld** [comment]
Doesn't look like the Windows builds liked that much at all:
```
thriftmd.lib(TSSLSocket.obj) : error LNK2001: unresolved external symbol OPENSSL_init_ssl [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
thriftmd.lib(TSSLSocket.obj) : error LNK2001: unresolved external symbol TLS_method [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
thriftmd.lib(TSSLSocket.obj) : error LNK2001: unresolved external symbol SSL_CTX_set_options [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
thriftmd.lib(TSSLSocket.obj) : error LNK2001: unresolved external symbol OPENSSL_sk_pop_free [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
thriftmd.lib(TSSLSocket.obj) : error LNK2001: unresolved external symbol OPENSSL_sk_value [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
thriftmd.lib(TSSLSocket.obj) : error LNK2001: unresolved external symbol OPENSSL_sk_num [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
thriftmd.lib(TSSLSocket.obj) : error LNK2001: unresolved external symbol OPENSSL_init_crypto [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
%SRC_DIR%\build\bin\Release\processor_test.exe : fatal error LNK1120: 7 unresolved externals [%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj]
Done Building Project "%SRC_DIR%\build\lib\cpp\test\processor_test.vcxproj" (default targets) -- FAILED.
Done Building Project "%SRC_DIR%\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
Done Building Project "%SRC_DIR%\build\install.vcxproj" (default targets) -- FAILED.
Build FAILED.

```

**Comment by dhirschfeld** [comment]
[This](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=12078&view=logs&jobId=2cc45e14-23e3-52d7-b33a-8c2744410b97&taskId=22e1f59c-6ad0-5e39-c80e-f2cebe3974dd&lineStart=446&lineEnd=452&colStart=1&colEnd=76) (`L446`) looks a bit suspicious:
```
	echo // > regress.gen.c
	echo #define NO_PYTHON_EXISTS > regress.gen.h
	python ..\event_rpcgen.py regress.rpc
  File "..\event_rpcgen.py", line 39
    print s
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?
```

**Comment by xhochy** [comment]
This won't work until https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/2e8fab70c729731ab89edfe19b328b9aae52e12e/recipe/conda_build_config.yaml#L459-L460 is updated.

**Pull request closed without merging**
